### ISSUE TITLE
Is this example working?

### ISSUE THREAD

**Issue by valeriyvan** [fyber-engineering/fairbid-sample-app-ios#21]
I could only see messages that ads are not available.

**Comment by saschabienert** [comment]
Thank you for raising this issue! You are right, the delivery of ads through the sample app is not guaranteed. This sample acts as a demonstration of best practices of integration, but when it comes to actually demonstrate the product it might fail due to the fact that we have no infrastructure to serve test ads. Therefore it will depend on factors like your country, your device your AAID/IDFA or any other kind of information that ad networks might have collected about you that are taken into consideration when placing a bid to show an ad to you.

You can try a VPN to a high demand region like the US.
We will take your feedback and add a disclaimer to our readme file.

**Comment by saschabienert** [comment]
[PR](https://github.com/fyber-engineering/fairbid-sample-app-ios/pull/22)
